[workspace]
authors = ["bwernest <ernest.laprelleboucher@gmail.com>"]
channels = ["conda-forge"]
name = "BetterWoxd"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
go = "python main.py"
dev = "python main_dev.py"
format = "autopep8 --in-place --recursive ./"
test = "pytest betterwoxd"

reset_cover = "coverage erase"
get_cover = "coverage run -m pytest betterwoxd test"
show_cover = "coverage html"
coverage = {depends-on = ["reset_cover", "get_cover", "show_cover"]}

[dependencies]
# Python
python = "3.13.*"
bs4 = "*"
requests = "*"
lxml = "*"

# Development
autopep8 = "*"
coverage = "*"
tqdm = "*"
pytest = "*"
